### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by DannyDarth** [BrandenEK/Windwaker-coop#32]
Is this still being worked on?

**Comment by BrandenEK** [comment]
Every couple of months or so I get pulled away to a different project but I always come back to this one.  If there is a specific problem or feature missing I will make sure that I get that taken care of asap though.  Otherwise, I will probably try to get back to work on v0.8 by the end of the month.

**Comment by DannyDarth** [comment]
True was just wondering. Would like to be able to see my friend if we play together. other mp mods for wind waker is just too buggy.

**Comment by BrandenEK** [comment]
Good point.  That is a major thing that will hopefully be coming soon.

**Comment by DannyDarth** [comment]
Awesome! Hopefully soon. We would love to use this mod.
